### ISSUE TITLE
Network.open is always false

### ISSUE THREAD

**Issue by alexandernst** [magne4000/node-libquassel#21]
The `open` attribute of each network is always `false`. I'm not sure if that is a bug in Quassel core, Quassel client (which I'm using while testing this library) or a bug in this library.

Extra question: how should I update the `open` property so it get's stored in the server?

**Comment by magne4000** [comment]
The open attribute is only handled by `quassel-webserver`, not by this lib.
So knowing this, it's impossible to store this parameter on the server (the open/close state is calculated upon connection/disconnection of a network)

**Comment by alexandernst** [comment]
I'm not sure to understand you. What is the `open` attribute? Does it hold the GUI state of a network? (if it's open or closed). Or does in hold the connected/disconnected state of a network? Or maybe it's something else?

Also, what do you mean by `quassel-webserver`?

**Comment by magne4000** [comment]
It holds the GUI state and has been moved into [quassel-webserver]( https://github.com/magne4000/quassel-webserver).
The `open` attribute still present in this lib can be considered as deprecated.

**Comment by alexandernst** [comment]
Oh, I see. So `open` is something that doesn't come from the quassel protocol itself, but it's just a leftover of a shared code between the library and the quassel-webserver?

If so, should this be removed in the next minor release?

**Comment by magne4000** [comment]
It should yes. In fact a full rewrite of this lib is coming really soon (you can check [es2015 branch](/magne4000/node-libquassel/tree/es2015)), so the current version (`0.*`) will soon be only in maintenance mode.

**Comment by alexandernst** [comment]
Oh, nice! Do you recommend me to use that branch instead of master for my project?

**Comment by magne4000** [comment]
Yep
