### ISSUE TITLE
CoreInfo update functionality

### ISSUE THREAD

**Issue by nitroxis** [magne4000/node-libquassel#8]
Hi. I have a feature request.
Could you add functionality to update the CoreInfo (the coreData variant map to be specific)? The client does that as well when you click File -> Core Info.
It'd be great to be able to check the number of clients connected to the core (sessionConnectedClients in coreData). With that, one can write a script to mark the user as "away" or rename the user when there are less than 2 clients connected.

**Comment by magne4000** [comment]
Added through 4bd502d (version 0.9.0)

Call it like this:
```javascript
quassel.sendInitRequest("CoreInfo", "");
```
You'll receive a `'coreinfo'` event:
```javascript
quassel.on('coreinfo', function(coredata) {
    console.log(coredata);
});
```
`coredata` object is not kept in sync (core limitation), so in order to refresh it, you must resend and InitRequest.
